### ISSUE TITLE
Help wanted - ways to control activation/deactivation of Update() function for BetterColorPicker

### ISSUE THREAD

**Issue by IDontHaveIdea** [ManlyMarco/KK_BetterColorPicker#1]
Hi,

BetterColorPicker works with KKS just resolved references compiled and works as intended.  I use this quite frequently.

I'm not new to programming I'm learning C# and mod programming.  A friend got me here.  Like many plugins I have seen they are called once every frame which is something I found inefficient you may not remember but I'm working with HCharaAdjustment.   I was able to control this behavior since the controller is derived from  CharaCustomFunctionController

public class HCharaAdjustController : CharaCustomFunctionController

There is gives access to a property **enabled** that when set to **false** Update() and company are not called.  I use kind of a wrapper function monitoring in SceneManager.sceneLoaded for HProc scene to load the activate.

I want to do the save for BetterColorPicker but I don't know enough and the frustration is starting to lurk around.  I been looking at the KKAPI reference but class is an obvious candidate to me.

Also the next step for HCharaAdjusmet is to save the delta vector of the movement if any and give the option to repeat the movement either manually or automatic.  Here pointers how to save and retrieve information, ID's for the animations.  Also is there a unique ID for cards/heroines.  This is the original petition. 

Workflow:

1. Load routine monitor for desired scene.  This consumes less resources than constants checks in Update() to see if work needs to be done.
2. Desired scene patch methods activate plugin
3. Exit scene in OnDestroy un-patch methods deactivate plugin
4. Continue monitoring for scene

Fast computers that have to be throttle down to 60 FPS won't get to much benefit but I think if this is promoted  as a good practice lower level machines will benefit.

Sorry if this is not the right forum for all this rant.  

Going to inspect the code of KKAPI later anyway.

Thanks in advance.

**Comment by ManlyMarco** [comment]
Hello!

The overhead of the Update calls by themselves is miniscule compared to most other things that are easier to fix. I suggest using a profiler first and either tackling high run time methods, or high garbage producer methods (first for more FPS, second for less stutter). We've spent a lot of time optimizing KK and most of the CPU time was spent in game code or in particularly bad methods in some plugins (which we fixed).

CharaCustomFunctionController inherits from MonoBehavior and itself uses some of the event methods. If you want to disable it then make sure to test your code because it might cause additional events to be fired (OnEnabled) or some events to be missed (coordinate change) which could make things worse not better. I have plans on a more efficient API but the overhead is too small to make it worthwhile even in KK where there are hundreds of these objects being spawned in a generously modded game.

I use the enable trick myself in some plugins, but I tend to avoid it unless I use it with OnGui code because only in that case it brings a tangible benefit, while making the code harder to read and maintain (which is a major consideration since many of these plugins span 4 or more games and some had 3+ people over development).

Patching during loading to a H scene is a good idea to lower boot time (it's more important with loading resources though), but unpatching is a waste of time since the H scene methods are only going to be fired inside said H scene. In case of plugins that only work inside H scenes it's better to either spawn a new monobehavior with the functionality and let it be destroyed by the scene unloading, or hook one of the H scene class' update methods and run your code in that.

If you have a working KKS version of this plugin then by all means make a PR for it, I really don't get enough of these :(

If you want to discuss more about what and why in these plugin sources, I suggest talking in the mod-programming channel on the Koikatsu discord server.
